require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CurriculumsSubjectsController do

  # This should return the minimal set of attributes required to create a valid
  # CurriculumsSubject. As you add validations to CurriculumsSubject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all curriculums_subjects as @curriculums_subjects" do
      curriculums_subject = CurriculumsSubject.create! valid_attributes
      get :index
      assigns(:curriculums_subjects).should eq([curriculums_subject])
    end
  end

  describe "GET show" do
    it "assigns the requested curriculums_subject as @curriculums_subject" do
      curriculums_subject = CurriculumsSubject.create! valid_attributes
      get :show, :id => curriculums_subject.id
      assigns(:curriculums_subject).should eq(curriculums_subject)
    end
  end

  describe "GET new" do
    it "assigns a new curriculums_subject as @curriculums_subject" do
      get :new
      assigns(:curriculums_subject).should be_a_new(CurriculumsSubject)
    end
  end

  describe "GET edit" do
    it "assigns the requested curriculums_subject as @curriculums_subject" do
      curriculums_subject = CurriculumsSubject.create! valid_attributes
      get :edit, :id => curriculums_subject.id
      assigns(:curriculums_subject).should eq(curriculums_subject)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CurriculumsSubject" do
        expect {
          post :create, :curriculums_subject => valid_attributes
        }.to change(CurriculumsSubject, :count).by(1)
      end

      it "assigns a newly created curriculums_subject as @curriculums_subject" do
        post :create, :curriculums_subject => valid_attributes
        assigns(:curriculums_subject).should be_a(CurriculumsSubject)
        assigns(:curriculums_subject).should be_persisted
      end

      it "redirects to the created curriculums_subject" do
        post :create, :curriculums_subject => valid_attributes
        response.should redirect_to(CurriculumsSubject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curriculums_subject as @curriculums_subject" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurriculumsSubject.any_instance.stub(:save).and_return(false)
        post :create, :curriculums_subject => {}
        assigns(:curriculums_subject).should be_a_new(CurriculumsSubject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CurriculumsSubject.any_instance.stub(:save).and_return(false)
        post :create, :curriculums_subject => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested curriculums_subject" do
        curriculums_subject = CurriculumsSubject.create! valid_attributes
        # Assuming there are no other curriculums_subjects in the database, this
        # specifies that the CurriculumsSubject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CurriculumsSubject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => curriculums_subject.id, :curriculums_subject => {'these' => 'params'}
      end

      it "assigns the requested curriculums_subject as @curriculums_subject" do
        curriculums_subject = CurriculumsSubject.create! valid_attributes
        put :update, :id => curriculums_subject.id, :curriculums_subject => valid_attributes
        assigns(:curriculums_subject).should eq(curriculums_subject)
      end

      it "redirects to the curriculums_subject" do
        curriculums_subject = CurriculumsSubject.create! valid_attributes
        put :update, :id => curriculums_subject.id, :curriculums_subject => valid_attributes
        response.should redirect_to(curriculums_subject)
      end
    end

    describe "with invalid params" do
      it "assigns the curriculums_subject as @curriculums_subject" do
        curriculums_subject = CurriculumsSubject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurriculumsSubject.any_instance.stub(:save).and_return(false)
        put :update, :id => curriculums_subject.id, :curriculums_subject => {}
        assigns(:curriculums_subject).should eq(curriculums_subject)
      end

      it "re-renders the 'edit' template" do
        curriculums_subject = CurriculumsSubject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CurriculumsSubject.any_instance.stub(:save).and_return(false)
        put :update, :id => curriculums_subject.id, :curriculums_subject => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curriculums_subject" do
      curriculums_subject = CurriculumsSubject.create! valid_attributes
      expect {
        delete :destroy, :id => curriculums_subject.id
      }.to change(CurriculumsSubject, :count).by(-1)
    end

    it "redirects to the curriculums_subjects list" do
      curriculums_subject = CurriculumsSubject.create! valid_attributes
      delete :destroy, :id => curriculums_subject.id
      response.should redirect_to(curriculums_subjects_url)
    end
  end

end
